#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

PROJECT="consts-quizzes"
HANDLER="https://${PROJECT}.firebaseapp.com/__/auth/handler"

banner "Sign in with X for const's quizzes"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "X developer account"
say "X needs a developer account before it will issue keys. Free tier is"
say "enough: this only ever reads a profile."
open_url "https://developer.x.com/en/portal/dashboard"
step "Sign in as the account that should own the app."
step "If prompted, sign up for the Free plan and accept X's Developer"
step "Agreement — that agreement is yours to accept, not something a script"
step "should click through on your behalf."
pause "Signed in and on the dashboard?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the app"
say "One project, one app inside it. The names are only ever shown to you"
say "and on the X consent screen."
open_url "https://developer.x.com/en/portal/projects-and-apps"
step "Click '+ Create Project'. Name it: const's quizzes"
step "Use case: 'Making a bot' or 'Exploring the API' — either is fine."
step "When it asks for an App, name it: consts-quizzes-web"
pause "App created?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Callback URL — the step that goes wrong"
say "This one is worth getting exactly right. X's OAuth always returns to"
say "Firebase's default handler, so a custom domain here produces"
say "'missing initial state' or 'invalid-credential' and nothing explains why."
printf '\n'
step "Open your app → 'User authentication settings' → Set up."
step "Turn ON 'Request email from users' only if you want it (not needed)."
step "App permissions: Read"
step "Type of App: Web App"
printf '\n'
say "${BOLD}Callback URI / Redirect URL — copy this exactly:${RESET}"
printf '\n    %s%s%s\n\n' "$GREEN" "$HANDLER" "$RESET"
say "Website URL: https://${PROJECT}.web.app"
step "Save."
pause "Saved, with that exact callback URL?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Keys → Firebase"
say "Paste the two values below and this wizard hands them straight to"
say "Firebase Auth. They are not written to disk, not echoed, and not kept"
say "anywhere on this machine — they belong in exactly one place."
open_url "https://developer.x.com/en/portal/projects-and-apps"
step "Open the app → 'Keys and tokens' tab."
step "Under 'Consumer Keys', click Regenerate (or View) on API Key & Secret."
printf '\n'
ask_secret X_API_KEY "API Key:"
ask_secret X_API_SECRET "API Key Secret:"

if [[ -z "$X_API_KEY" || -z "$X_API_SECRET" ]]; then
  warn "both values are needed; re-run when you have them"
  exit 1
fi

say "Enabling twitter.com on Firebase project ${PROJECT}…"
TOKEN=$(gcloud auth print-access-token)
BODY=$(printf '{"enabled":true,"clientId":"%s","clientSecret":"%s"}' \
  "$X_API_KEY" "$X_API_SECRET")
BASE="https://identitytoolkit.googleapis.com/admin/v2/projects/${PROJECT}/defaultSupportedIdpConfigs"

# Create first; if the provider already exists, update it instead.
RESULT=$(curl -s -X POST "${BASE}?idpId=twitter.com" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-goog-user-project: ${PROJECT}" \
  -d "$BODY")

if printf '%s' "$RESULT" | grep -q '"error"'; then
  RESULT=$(curl -s -X PATCH \
    "${BASE}/twitter.com?updateMask=enabled,clientId,clientSecret" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -H "x-goog-user-project: ${PROJECT}" \
    -d "$BODY")
fi
unset X_API_KEY X_API_SECRET BODY

if printf '%s' "$RESULT" | grep -q '"error"'; then
  warn "Firebase refused the credentials:"
  printf '%s\n' "$RESULT" | head -5
  SKIPPED+=("enable twitter.com in the Firebase console by hand")
else
  printf '  %s✓%s twitter.com enabled on %s\n' "$GREEN" "$RESET" "$PROJECT"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check it took"
say "Reading the provider back from Firebase."
CHECK=$(curl -s "${BASE}" \
  -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  -H "x-goog-user-project: ${PROJECT}")
printf '%s' "$CHECK" | python3 -c '
import sys, json
for c in json.load(sys.stdin).get("defaultSupportedIdpConfigs", []):
    name = c["name"].split("/")[-1]
    print(f"    {name}: enabled={c.get(\"enabled\")} clientId={bool(c.get(\"clientId\"))}")
' || say "    (could not parse the response)"
printf '\n'
say "Now try it for real:"
step "Open https://${PROJECT}.web.app"
step "Click your handle, top right, then 'Connect X'."
step "You should keep your handle and gain your X name, picture and banner."
printf '\n'
say "If it fails with 'missing initial state', the callback URL in stage 3"
say "is wrong — it must be the firebaseapp.com one, not the web.app one."

finish
